LA-0000 Add permission script for bigquery
lightbeamai/lb-installer pull request #38
Opened 2023-07-24 15:35 UTC by kaif-lb

2023-07-24 15:46 UTC, arpit-lb requested changes
Please put correct ticket ID in the title.

2023-07-24 15:46 UTC, arpit-lb commented on sql_user_check_bigquery/README.md
> +gcloud auth activate-service-account  --key-file=<service-account.json file path> --project=<project id>
Add in readme what's the project ID and how a user is supposed to acquire this value

2023-07-31 09:54 UTC, arpit-lb requested changes

2023-07-31 09:54 UTC, arpit-lb commented on sql_user_check_bigquery/README.md
> +
```suggestion
### Run the script

Run the following command from `sql_user_check_bigquery` directory

```

2023-08-01 05:33 UTC, kaif-lb commented on sql_user_check_bigquery/README.md
> +MODE=stats DATASETID=<dataset id> OUTPUT=<output file path>  bash run.sh
added support for:
- multiple datasetIDs
- 0 datasetID

2023-08-01 09:41 UTC, arpit-lb approved these changes

2023-08-07 05:53 UTC, merged