Update master.sh
lightbeamai/lb-installer pull request #64
Opened 2024-03-15 16:54 UTC by mehul-lb

Some updates as per https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate

2024-03-16 00:07 UTC, ajay-lb commented on Ubuntu/master.sh
> +mkdir mkdir /etc/apt/keyrings
```suggestion
mkdir /etc/apt/keyrings
```

2024-03-16 00:10 UTC, mehul-lb reviewed
Updated

2024-03-16 00:12 UTC, ajay-lb approved these changes

2024-03-20 00:24 UTC, aditya-lb requested changes

2024-03-20 00:24 UTC, aditya-lb commented on Ubuntu/master.sh
> +# Doc https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate
```suggestion
# For versions older than 22.04, the /etc/apt/keyrings directory does not exist by default so it needs to be created. See https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate for more details.
```

2024-03-20 00:24 UTC, aditya-lb commented on Ubuntu/master.sh
> +mkdir /etc/apt/keyrings
```suggestion
mkdir -p /etc/apt/keyrings
```

2024-05-16 16:26 UTC, closed without merging